name: Keep scheduled workflow activity

on:
  push:

permissions:
  actions: write

jobs:
  keep-scheduled-workflow-activity:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sed -i '4c .spawn("bash", [`${__dirname}/entrypoint.sh`], { cwd: __dirname, stdio: "inherit" })' /home/runner/work/_actions/WaterLemons2k/scheduled-workflow-activity-action/v1/index.js
      - name: Keep scheduled workflow activity
        uses: WaterLemons2k/scheduled-workflow-activity-action@v1
