name: Keep scheduled workflow activity

on:
  push:

permissions:
  actions: write

jobs:
  keep-scheduled-workflow-activity:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat /home/runner/work/_actions/WaterLemons2k/scheduled-workflow-activity-action/v1/colors.sh
      - name: Keep scheduled workflow activity
        uses: WaterLemons2k/scheduled-workflow-activity-action@v1
