name: Keep scheduled workflow activity

on:
  push:

permissions:
  actions: write

jobs:
  keep-scheduled-workflow-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sh colors.sh
      - name: Keep scheduled workflow activity
        uses: WaterLemons2k/scheduled-workflow-activity-action@v1
        with:
          workflows: 1 blank.yml a
